name: comment on pull request

on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    permissions: # This job requires write access to issues in order to add labels and comment.
      pull-requests: write
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v2.3.1
        with:
          message: |
            congratz
